---
version: "3.5"

services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_DB: 'headscale'
    ports:
        - 5432:5432



